substitutions:
  device_name: "mercury-206-es"
  device_ip: 192.168.1.XXX
  device_description: "Мониторинг эл. счетчика Меркурий"
  board: esp32dev
  platform: esp32
  type: arduino

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  comment: ${device_description}

${platform}:
  board: ${board}
  framework:
    type: ${type}

# Подключаем локальную папку с компонентами
external_components:
  - source: 
      type: local
      path: my_components
# Настройка логирования и API
logger:
  level: debug

ota:
- platform: esphome  
  password: !secret ota_password

api:
  encryption:
    key: !secret encryption_key

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN

  phy_addr: 1
  power_pin: GPIO16

  manual_ip: 
    static_ip: ${device_ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

web_server:
  port: 80
  include_internal: true
  auth:
    username: !secret web_server_login
    password: !secret web_server_password
debug:
  update_interval: 5s

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO5
  baud_rate: 9600

# Инициализируем основной контроллер
mercury:
  id: my_meter
  update_interval: 500ms
  # Здесь можно добавить серийный номер если вынести его в конфиг
  serial_number: XXXXXX

# Подключаем сенсоры к контроллеру
sensor:
  - platform: mercury
    voltage:
      name: "mercury_voltage"
      device_class: voltage
      state_class: measurement
      icon: "mdi:alpha-v-circle-outline"
      unit_of_measurement: "V"
      accuracy_decimals: 1

    current:
      name: "mercury_current"
      device_class: current
      state_class: measurement
      icon: "mdi:alpha-a-circle-outline"
      unit_of_measurement: "A"
      accuracy_decimals: 2

    power:
      name: "mercury_power"
      device_class: power
      state_class: measurement
      icon: "mdi:alpha-p-circle-outline"
      unit_of_measurement: "W"
      accuracy_decimals: 0

    t1:
      name: "mercury_t1_energy"
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing

    t2:
      name: "mercury_t2_energy"
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing


    t3:
      name: "mercury_t3_energy"
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2
      device_class: energy
      state_class: total_increasing
      
    total:
      name: "mercury_sum_tariff"
      icon: "mdi:counter"
      unit_of_measurement: "kWh"
      accuracy_decimals: 2

    frequency:
      name: "mercury_frequency"
      icon: "mdi:sine-wave"
      device_class: frequency
      state_class: measurement
      unit_of_measurement: "Hz"
      accuracy_decimals: 2

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"


#Uptime - показывает сколько устройство работает в сети. Тоже нужно было для отпладки.
  - platform: uptime
    name: ${device_name} uptime
    id: uptime_sensor
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).get_raw_state());
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: mercury
    datetime:
      name: "mercury_datetime"
  - platform: version
    name: ${device_name} version
    hide_timestamp: true

  - platform: template
    name: ${device_name} uptime
    id: uptime_human
    icon: mdi:clock-start

  - platform: debug
    reset_reason:
      name: "Reset Reason"